version: '3.8'

services:

  # relayer:

  # blockchain:

  web:
    build: ./web
    command: uvicorn api.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./web:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo
